---
version: '3.4'
services:
  webserver:
    image: webserver
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
  typhon-text-processing:
    image: typhon-text-processing
    hostname: typhon-text-processing
    build:
      context: .
      dockerfile: Dockerfile
