---
version: '3.4'
services:
  webserver:
    image: webserver
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 81:80
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8088'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.17.5
    hostname: weaviate
    # ports:
    # - 8088:8088
    restart: on-failure:0
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8088'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      CLUSTER_HOSTNAME: 'node1'
  t2v-transformers:
    image: text2vec-typhon
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENABLE_CUDA: '0'
